project:
  type: website
  output-dir: docs

website:
  reader-mode: true
  title: "Vladimir Sanchez Tenjo"
  description: "Portafolio profesional en Estadística y Ciencia de Datos. Incluye proyectos en R, Power BI y análisis estadístico."
  site-url: "https://vladsanten.github.io"   # URL de tu sitio en GitHub Pages
  open-graph: true     # Metadatos para compartir en redes
  twitter-card: true   # Tarjeta de previsualización para Twitter/X
  navbar:
    background: primary # light
    search: true
    left:
      - text: 'Principal'
        href: index.qmd
      - text: 'Acerca de Mí'
        href: about.qmd
      - sidebar:recursos
      - sidebar:programas
      - sidebar:pasatiempos

  sidebar:
    - id: recursos
      title: "Recursos de aprendizaje"
      style: "docked"
      background: light
      collapse-level: 1
      contents:
        - text: "Libros de Texto"
          href: Recursos1.qmd
        - text: "Recursos de Multimedia"
          href: Recursos2.qmd
        - text: "Otros"
          href: Libros_0001.qmd
    - id: programas
      title: "Proyectos"
      style: "docked"
      background: light
      collapse-level: 1
      contents:
        - text: "Serie de Tiempo - Ejercicio"
          href: Series_Tesuvr.qmd
        - text: "RStudio Básico"
          href: R_Tutorial_01.qmd
        - text: "Power BI"
          href: Recursos3.qmd
        - text: "Trabajo Grado"
          href: Trabajo_Grado.qmd
    - id: pasatiempos
      title: "Otros intereses y recursos"
      style: "docked"
      background: light
      collapse-level: 1
      contents:
        - text: "Podcast"
          href: Podcast.qmd
        - text: "Libros"
          href: Libros_02.qmd
        - text: "Películas"
          href: Peliculas.qmd

format:
  html:
    theme: journal
    css: styles.css
    toc: true
