---
title: "Literatura"
format: html
---

# Literatura

La literatura ha sido otro de mis grandes intereses, una forma de diálogo con las grandes ideas, la filosofía y la belleza del lenguaje. Estos son algunos de los libros y autores que más me han marcado:

- *Así habló Zaratustra* - F. Nietzsche  
- *La gaya ciencia* - F. Nietzsche  
- *Más allá del bien y del mal* - F. Nietzsche  
- *Siddhartha* — H. Hesse  
- *El lobo estepario* - H. Hesse  
- *El libro del desasosiego* - F. Pessoa  
- *Cómo leer y por qué* - Harold Bloom
- *Cómo hablar de libros que no se han leído* - P. Bayard
- *Fragmentos* -  G. Steiner  
- *Elogio del Caminar* - D. Le Breton  
- *El tatuaje* - D. Le Breton  
- *Ensayos y poemas* — P. Valéry  
- *No leer* — A. Zambra  
- *Esto es agua* - D. F. Wallace
- *El lector* - B. Schlink
- *Cartas a un joven disidente* - C. Hitchens
- *De que hablo cuando hablo de correr* - H. Murakami
- *De que hablo cuando hablo de escribir* - H. Murakami
- *Tao Te King* - Lao Tsé
- *I Ching. El libro de las mutaciones* - R. Wilhelm
- *Poemas de la locura* - Friedrich Hölderlin
- *No hay nadie en casa* - D. Ugrešić
- *Una ofrenda musical* - L. Sagasti 
- *Mishima o la visión del vacío* - M. Yourcenar
- *Los Upanishad esenciales* - Pensamiento Hindu
- *El Aleph* - J. L Borges
- *Inquisiciones* - J. L Borges
- *Yo, etcétera* - S. Sontang
- *María Antioneta* S. Zweig
- *El tiempo en la historia* - G. J. Whitrow
- *El extraño caso del Dr. Jekyll y Mr. Hyde* - R. L. Stevenson
- *El decamerón* - G. Boccaccio
- *Asesinatos S.L.* - J. London & R. L. Fish
- *Antifrágil* - N. Taleb
- *Silencioso tao* - R. Smullya
- *Meditaciones sobre la vida* - N. Robert	 
- *Ejercicios de estilo* - Q. Raymond
- *El ABC de la lectura* - E. L. Pound
- *El ojo y el espiritu* - M. Merleau-Ponty
- *El Aprendiz de Mago* - E. Rosero 
---

## Nota personal

Esta lista no es exhaustiva ni pretende ser un canon, sino un registro de aquellas lecturas que han dejado huella en mi forma de pensar y sentir.
---
