---
title: "Podcast"
editor: visual
---

# 🎙️ Podcasts recomendados

En esta sección comparto algunos de los podcasts que escucho, una mezcla de los que siguen activos y otros que ya no producen episodios, pero que siguen siendo muy valiosos. 

## 🔹 Actuales
- **Lex Fridman Podcast**  
  Conversaciones profundas sobre inteligencia artificial, tecnología, ciencia y filosofía.  

- **The Diary of a CEO (Stephen Bartlett)**  
  Entrevistas inspiradoras con líderes, emprendedores y creadores de impacto.  

- **Radio Ambulante**  
  Historias latinoamericanas narradas con gran calidad periodística y humana.  

- **TED Talks Daily**  
  Ideas y conferencias de TED en formato breve y accesible.  

- **Diana Uribe.fm**  
  Historia, cultura y análisis contados con un estilo cercano y narrativo.  
  
- **BBVA Aprendemos juntos 2030**  
  Entrevistas inspiradoras con diferentes personas a cerca de como afrontar la vida de la mejor manera a partir de herramientas, conocimientos y experiencias. 
  
- **mixxi.io**  
  Podcast diario de tecnología que explica la actualidad de una forma amena, clara y consisa.
  
- **Quillete Podcast**  
  Debates academicos sobre ciencia, política,filosofia y cultura.
  
- **La Fonda Filosófica**  
  Ideas de la filosofia explicadas de manera clara.

- **La Muralla y los Libros**  
  Conversaciones sobre producción literararia, ferias, talleres, editoriales, libros, eventos. (Argentina)

- **Descarga Cultura (UNAM)**  
  Literatura contemporanea, clásicos universales, música, teatro, etc.

- **La filosofía no sirve para nada**  
  Refexiones sobre temas actuales desde la ciencia y la filosofía.

- **La biblioteca de Julio**  
  Sobre el universo de Julio Cortazar

- **Huberman Lab**  
  Exploración de temas de neurociencia.


## 🔹 Pausados o finalizados
- **El Test de Turing**  
  Conversaciones sobre inteligencia artificial, filosofía y futuro tecnológico.  

- **DOAC** (*nombre completo por confirmar*)  
  Exploración crítica de temas actuales en ciencia y sociedad.
  
- **El Oficio de leer**  
  Exploración crítica de temas actuales en ciencia y sociedad.
  
- **El resto es literatura**  
  Biografías y libros.

- **Como funcionan las cosas**  
  Narraciones singularidades sobre como 'funcionan' diferentes cosas/temas desde la 
  soledad  hasta 'dejar de funcionar'.
 
- **A Fondo** 
Recopilación de los audios de las entrevistas del programa "A Fondo" emitido por la televisión pública española (TVE) entre los años 1976 y 1981, dirigido y presentado por el periodista Joaquín Soler Serrano.
  
