---
title: "Preguntas, ideas, pensamientos a partir de podcast."
editor: visual
---

Acá residen algunas de las cosas que mas me llamaron la atención de lo que escuche en cada uno de estos <em>textos</em>. Mucho de esto serán citas textuales/literales, en algunas ocaciones hare comentarios desde mi ignoracia tratado de enriquecer esto...

<!---
<h2>Como podemos acceder a nuestra conciencia </h2>
--->

<h3> <center> Lex Fridman Podcast </center></h3>

<ul style = "list-style-type:circle">
  <li> <b> Episodio #393. Andrew Huberman: Relaciones, Drama, Traición, Sexo y Amor </b></li>
  
  <ol>
  <li> Como podemos acceder a nuestra conciencia...</li>
  <li>Tea</li>
  <li> Sobre tener hijos en familia: <em> Los hijos aportan un tremendo significado a nuestras vidas, seriamos unos idiotas si no formamos  familia...</em></li>
  </ol> 
  
 <p> Palabras de A. Camus citadas por Lex: <em> En medio del invierno descubri  que  dentro de mi existia  un verano invencible  </em></p>
 
A continuación, me permito extender el texto, ya que esta cita pertenece a uno de mis autores de referencia. Se trata de uno de sus libros más personales, tanto a nivel biográfico como en cuanto a la calidad de la prosa...
  <blockquote>
  <em>
  A mediodía, sobre las laderas medio arenosas y cubiertas por heliotropos como por una espuma que hubieran dejado al retirarse las olas furiosas de los últimos días, miraba el mar, que a esa hora se agitaba apenas con un movimiento fatigado, y calmaba esa doble sed que no se puede engañar mucho tiempo sin que el ser se seque, quiero decir amar y admirar.<b> En no ser amado sólo hay mala suerte: en no amar hay desgracia. Hoy en día todos morimos de esa desgracia.</b> Porque la sangre, los odios, descarnan el corazón; la prolongada reivindicación de la justicia agota el amor que, sin embargo, la hizo nacer. En el clamor en que vivimos, el amor es imposible y la justicia no basta. Por eso Europa odia el día y no sabe más que oponer injusticia a la injusticia. Pero para impedir que la justicia, hermoso fruto naranja que no contiene más que una pulpa amarga y seca, se agoste, volvía a descubrir en Tipasa que había que guardar intactas dentro de uno mismo una frescura, una fuente de alegría; amar el día que escapa a la injusticia y volver al combate con esa luz conquistada. Volvía a encontrar allí la antigua belleza, un cielo joven, y ponderaba mi suerte, comprendiendo por fin que en los peores años de nuestra locura el recuerdo de este cielo no me había abandonado nunca. Era él quien, para concluir, me había impedido perder la esperanza. Yo había sabido siempre que las ruinas de Tipasa eran más jóvenes que nuestras obras en construcción o nuestros escombros. El mundo empezaba allí cada día con una luz siempre nueva. ¡Oh, luz!, ése es el grito de todos los personajes enfrentados, en el drama antiguo, a su destino. Ese último recurso era también el nuestro y ahora yo lo sabía. <b>En mitad del invierno aprendía por fin que había en mí un verano invencible</b>.  </em>
  <br>Tomado de  <em>"Retorno a Tipasa"</em> en su libro <em>"El verano"</em> </br>

 
  </blockquote>

<hr> </hr>
  <li> <b>Episodio #403 - Lisa Randall: Materia Oscura, Física Teórica y Eventos de Extinción</b></li>
  
<ol>
<li> ¿Como se antropomorfisa la materia oscura?</li>
<li> ¿La materia oscura tiene alguina estructura que le permite interactua internamente, como lo hace la materia estandar con las fuerzar/interacciones conocidas (gravitacional, nuclear débil, electromagnética, nuclear fuerte)?</li>
<li> ¿Que forma tiene la materia oscura?</li>
<li> ¿Como podemos medir aquello que no vemos?</li>
<li> ¿Es mas probable que perescamos debido a una extincion causada por acontecimientos/eventos generados por humanos o por otros exteriores al nivel solar/galactico ?</li>
<li> ¿Como experimentaron los dinosuarios la extinción? (Esta pregunta planteada por Lex va mas hacia la experiencia visula del impacto del meteorito)</li>

<li> Cita mencionada por sobre el libro de la autora acerca de abordar lo bello/sublime en la fisica (y en el conocimiento en geeral, agregaria):
<blockquote>
<em> ¿Quién, si gritara yo, me escucharía <br> en los celestes coros? Y si un ángel <br>inopinadamente me ciñera<br> contra su corazón, la fuerza de su ser<br> me borraría;<b> porque la belleza no es<br> sino el nacimiento de lo terrible; un algo<br> que nosotros podemos admirar y soportar<br> tan sólo en la medida en que se aviene,<br> desdeñoso, a existir sin destruirnos</b>. <br>Todo ángel es terrible. </em>
<p>Tomado de la <em>Primera Eliegía</em> del libro <em>Elegías de Duino</em> de <em>R. M. Rilke</em></p>
</blockquote>
</li>
<li> ¿Puede existir algo analogo a lo que es la vida-inteligente en el campo de la materia oscura? Es decir, si bien en el <em>plano</em> de la materia ordinaria (<em>materia bariónica</em>), se ha generado todo lo que posemos observar y nombramos como realidad. ¿ Que implicaria que esto pasara dentro de la materia oscura, algun tipo de interaciones complejas que dieran origen a sistemas mas elaborados?</li>
<li>¿ Qué es el modelo estándar de particulas, como genera/sostiene todo el funcionamiento de la realidad y como encaja la <em>materia oscura</em> en este modelo?</li>
<li>¿Puede la ciencia descubrir la realidad?</li>
<li> La respuesta dada por Lissa a la pregunta retórica echa por Lex (¿Cuales crees son los limites de la ciencia?) me parece muy sugestiva y convincente.
<blockquote>
<cite>
- Soy lo suficientemente inteligente como para saber que no tengo idea, y además ni siquiera esta claro que es/significa  <em>'ciencia'</em>. Porque existe la ciencia que hacemos, que la fisica de particulas en la que tratamos encontrar cosas fundamentales y descubrir cuales son sus efectos. Hay ciencias como la biología, que se encuentra en un nivel superior en la que el tipo de preguntas que aborda/hace y formas de medir/contrastar es diferentes. Ahora bien el tipo de ciencia que sucedera en una epoca/era mas númerica o incluso de IA o algo así; ¿que significará responder una pregunta: significa que podemos predecirlo, significa que reproducirlo? Por tanto
creo que nos estamos encontrando con una especie de redefinición de lo entendemos de ciencia como seres humanos. Entonces en términos de la ciencia que actualmente se hace no creo que podamos responder a esa pregunta hasta que llegemos allí... Si piensas en cuanto a avanzado la ciencia en el último siglo o siglo y medio, es increible...
<br>
Creeria que es prematuro, decir que se conocen las limitaciones...
</cite>    
</blockquote>
</li>
<li> ¿Cual es para ti, la diferencia entre fisica y matemáticas, en la forma en que nos ayudan a comprender el mundo?</li>
<blockquote>
<cite>
- Creo que existe mucha más superposición entre estas dos, de la que realmente se aprecia...
<br> Una vez más las preguntas que se abordan son diferentes en cada área.</br>
A los matemáticos les gusta la estructura misma, los físicos se tratan de concentrar en las consecuncias para el mundo...
Se convierte casi en una cuestión sociologica, de cuanto deberia ser uno u otro. Creo que uno puede quedar atrapado en los problemas mismos, y aveces en los metodos y simplemente hacer otros ejemplos.
Por lo tanto los verdaderos conocimientos sobre fisica, a menudo provienen de personas que piensan tanto en fisicas como en matemáticas.
</cite>
</blockquote>
<li> <code>57:25</code> Acerca de las implicanciones de la IA la forma en que va afectar el futuro y la ciencia en particular, Lex plantea la siguiente pregunta que me resulta muy importante y curiosa: ¿Que tan especiales son los humanos, para poder descubrir ideas/conocimientos nuevas sobre el universo/cosmos?</li>
<blockquote>
<cite>
Depende de que tipo de conocimiento y que vamos a descubrir, porque es dificil pensar el algo que no existe...digo
se podria dar un paso atras con internet (es como un poco intentar manejar cuatro dimensiones, volver a tres dimensiones para regresar a algo que puedes imaginar), así que puedes decir muchas cosas en un nivel muy diferente acerca de internet. Se puede decir que a ayudado a muchas cosas, 
tomo vida en cierto sentido; pero es algo que podemos domesticar... 
Yo misma no hubiese podido escribir libros si internet no existiera, porque no abria tenido tiempo de ir a la biblioteca y buscarlo todo... En cierto sentido la IA podria ser una herramienta que nos ayude a ir un paso mas allá de lo que hacemos y de una forma mas eficiente, como ya lo esta haciendo.
O bien podria ser la parte opuesta, como la parte de internet que no podemos controlar que esta arruinando la politica... Luego existen cosas más grandes sobre las cuales la gente especula, acerca que la IA puede hacer sus propias cosas... pero en términos de resolver las cosas estamos en las primeras etapas
</cite>
</blockquote>
<li> Los grandes modelos de lenguaje son mas o menos generalizaciones de cosas qeu tenemos </li>
<li> <code>1:02:35</code>(Pregunta de Lex a Lisa) ¿Cual es para ti, el problema sin resolver mas hermoso/interesante de la fisica?</li>

<blockquote>
<cite>
- La mayoria de las preguntas, las <em>grandes preguntas</em>, tienen que ver con lo que subyace a las cosas como: ¿Cual fue su origen? ¿Que hay en su base?... Tambien existen preguntas basicas: ¿A donde nos llevara la ciencia? ¿Cuanto podemos enterder?... Hay preguntas del corte
¿Como llegamos aquí? ¿Que subyace a esto?... Hay preguntas muy profundas como: 
¿Que fracción estamos viendo realmente? ¿Si existe otras fuerzas, si hay otra forma de ver lo que nos rodea? ¿Existen universos mas allá del nuestro? Si son tan diferentes, ¿Como podemos siquiera comprenderlos, detectarlos?... Hay mucho que ver con ir más allá. Siempre se trata de ir mas allá de nuestra experiencia y visión limitadas, y tratar  de ver lo que hay detrás, tanto a pequeña como gran escala...Simplemente no sabemos las respuestas... Me gustaria pensar que entendemos más sobre materia oscura, energia oscura, dimensiones adicionales, etc; Cosas en la que se esta trabajando, porque probablemente existe mucho más allá de lo que se ha encontrado y que esta por decubrir.

</cite>
</blockquote>

<li> ¿La física puede cambiar mas alla del universo observable?</li>

<li> <code>1:05:25</code>Consejo para los jovenes cientificos.</li>
<blockquote>
<cite>
- Deben creer firmemente en lo que haces y al mismo tiempo cuestionarlo a todo momento...Lograr ese equilirio, a veces ayuda colaborar con otros...
Saber que puedes tener buenas y sabiendo que todas puedesn estar equivocadas... Una cuarda floja dificil de caminar, pero se debe hacer.
<br>
- Intentar descubrir por qué las cosas son como son...es bueno hacerlo desde un punto de vista teórico eficaz y un paso a la vez.
</br>
</cite>
</blockquote>
<li> ¿Lo que percibimos como bello/sublime se debe a como hemos evolucionado, ?</li>
</ol> 
"Lo importante es no dejar de cuestionarse. La curiosidad tiene su propia razón de ser."
<hr></hr>
  <li> Episodio #404 -</li>
</ul> 


<strong> Esto estara en otro sitio a futuro</strong>
