---
title: "Recursos de interés (enlaces)"
editor: visual
---

Algunos sitios/canales/enlaces con recursos de temas referentes a mis intereses

### Luis Rincón 

Profesor del Departamento de Matemáticas en la Facultad de Ciencias de la UNAM México 
- [El sitio personal (Opción 1)](http://lya.fciencias.unam.mx/lars/)
- [El sitio personal (Opción 2)](https://sites.google.com/ciencias.unam.mx/luis-rincon)
- [Canal de YouTube](https://www.youtube.com/@LuisRinconUNAM)

### Random Services
[Random Services](https://www.randomservices.org/) es un sitio web dedicado a la probabilidad, la estadística matemática y los procesos estocásticos, y está destinado a profesores y estudiantes de estas materias.

### Bookdown | bookdown.org
El sitio web [bookdown.org](https://bookdown.org/) es un servicio de RStudio, PBC, para alojar libros.

### Introduction to Data Technologies de Paul Murrell
[Introduction to Data Technologies](https://www.stat.auckland.ac.nz/~paul/ItDT/HTML/node89.html) Este libro/sitio trata sobre cuestiones y tecnologías relacionadas con el almacenamiento y uso de conjuntos de datos.

### Michael Clark
Sitio personal de [Michael Clark](https://m-clark.github.io/about.html)



